[package]
name = "para"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.11"
colored = "2.1.0"
markdown = "1.0.0-alpha.18"
toml = "0.5.2"
serde = "1.0.136"
serde_derive = "1.0.136"
homedir = "0.3.3"
